update cfn deploy

diff --git a/aws/bin/cfn-deploy b/aws/bin/cfn-deploy
--- a/aws/bin/cfn-deploy
+++ b/aws/bin/cfn-deploy
@@ -4,10 +4,15 @@ set -e
 
 TEMPLATE_FILE="$1"
 STACK_NAME="$2"
+INTERACTIVE="${3:-true}"
+
+CAPABILITIES="--capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
 
 if [[ -n "$3" ]]; then
-    PARAMETERS="--parameter-overrides ${@: 3}"
+    PARAMETER_OVERRIDES="--parameter-overrides ${@: 3}"
+    PARAMETERS="--parameters ${@: 3}"
 else
+    PARAMETER_OVERRIDES=""
     PARAMETERS=""
 fi
 
@@ -25,21 +30,37 @@ else
     NOTIFICATIONS=""
 fi
 
-if ! aws cloudformation deploy \
-    --template-file "$TEMPLATE_FILE" --stack-name "$STACK_NAME" \
-    $NOTIFICATIONS \
-    $PARAMETERS \
-    --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
-then
-    echo 'Stack create/update failed:'
-    aws cloudformation describe-stack-events --stack-name "$STACK_NAME" --max-items 30 \
-        --output yaml \
-        --query 'StackEvents[?contains(ResourceStatus, `_FAILED`)].{Status: ResourceStatus, Id: LogicalResourceId, Reason: ResourceStatusReason}'
-fi
+if [[ $INTERACTIVE = 'false' ]]; then
+    if ! aws cloudformation describe-stacks --stack-name="$STACK_NAME" --output text --query 'Stacks[0].StackStatus' >/tmp/stack-status 2>/dev/null; then
+        ACTION=create-stack
+    elif [[ "$(cat /tmp/stack-status)" = "ROLLBACK_COMPLETE" ]]; then
+        aws cloudformation delete-stack --stack-name "$STACK_NAME"
+        sleep 15
+        ACTION=create-stack
+    else
+        ACTION=update-stack
+    fi
+    aws cloudformation $ACTION --stack-name="$STACK_NAME" --template-body="$(cat "$TEMPLATE_FILE")" $NOTIFICATIONS $PARAMETERS $CAPABILITIES
 
-STATUS=$(aws cloudformation describe-stacks --stack-name="$STACK_NAME" --output text --query 'Stacks[0].StackStatus')
-if [[ $STATUS = "ROLLBACK_COMPLETE" ]]; then
-    aws cloudformation delete-stack --stack-name "$STACK_NAME"
+else
+    if ! aws cloudformation deploy \
+        --template-file "$TEMPLATE_FILE" --stack-name "$STACK_NAME" \
+        $NOTIFICATIONS \
+        $PARAMETERS \
+        $CAPABILITIES
+    then
+        echo 'Stack create/update failed:'
+        aws cloudformation describe-stack-events --stack-name "$STACK_NAME" --max-items 30 \
+            --output yaml \
+            --query 'StackEvents[?contains(ResourceStatus, `_FAILED`)].{Status: ResourceStatus, Id: LogicalResourceId, Reason: ResourceStatusReason}'
+    fi
+
+    STATUS=$(aws cloudformation describe-stacks --stack-name="$STACK_NAME" --output text --query 'Stacks[0].StackStatus')
+    if [[ $STATUS = "ROLLBACK_COMPLETE" ]]; then
+        aws cloudformation delete-stack --stack-name "$STACK_NAME"
+    fi
+
 fi
 
 rm /tmp/topic-arn
+rm /tmp/stack-status
